export const PUT_WALLET = "PUT_WALLET";
export const FETCH_CURRENT_WALLET = "FETCH_CURRENT_WALLET";
export const REFRESH_CURRENT_ADDRESSES = "REFRESH_CURRENT_ADDRESSES";
export const REFRESH_BALANCES = "REFRESH_BALANCES";
export const GET_CURRENT_PRICE = "GET_CURRENT_PRICE";
