export enum ACTIONS {
  INIT = "INIT",
  PUT_WALLET = "PUT_WALLET",
  LOAD_WALLETS = "LOAD_WALLETS",
  LOAD_SETTINGS = "LOAD_SETTINGS",
  SAVE_SETTINGS = "SAVE_SETTINGS",
  FETCH_AND_SET_AS_CURRENT_WALLET = "FETCH_AND_SET_AS_CURRENT_WALLET",
  REFRESH_CURRENT_ADDRESSES = "REFRESH_CURRENT_ADDRESSES",
  REFRESH_BALANCES = "REFRESH_BALANCES",
  LOAD_BALANCES = "LOAD_BALANCES",
  FETCH_CURRENT_PRICES = "GET_CURRENT_PRICE",
  SET_CURRENT_WALLET = "SET_CURRENT_WALLET"
}
