export enum ACTIONS {
  // default store
  INIT = "INIT",

  // wallet store
  PUT_WALLET = "PUT_WALLET",
  FETCH_AND_SET_AS_CURRENT_WALLET = "FETCH_AND_SET_AS_CURRENT_WALLET",
  REFRESH_CURRENT_ADDRESSES = "REFRESH_CURRENT_ADDRESSES",
  FETCH_BALANCES = "FETCH_BALANCES",
  REMOVE_WALLET = "REMOVE_WALLET",
  CHECK_PENDING_BOXES = "CHECK_PENDING_BOXES"
}
