export enum MUTATIONS {
  REMOVE_WALLET = "REMOVE_WALLET",
  UPDATE_BALANCES = "UPDATE_ADDRESSES_BALANCES",
  SET_LOADING = "SET_LOADING",
  SET_WALLET_SETTINGS = "SET_WALLET_SETTINGS",
  SET_DEFAULT_CHANGE_INDEX = "SET_DEFAULT_CHANGE_INDEX",
  SET_USED_ADDRESSES_FILTER = "SET_USED_ADDRESSES_FILTER"
}
