export enum MUTATIONS {
  SET_WALLETS = "SET_WALLETS",
  SET_CURRENT_WALLET = "SET_CURRENT_WALLET",
  SET_CURRENT_ADDRESSES = "SET_CURRENT_ADDRESSES",
  REMOVE_WALLET = "REMOVE_WALLET",
  ADD_ADDRESS = "ADD_ADDRESS",
  UPDATE_BALANCES = "UPDATE_ADDRESSES_BALANCES",
  SET_LOADING = "SET_LOADING",
  SET_WALLET_SETTINGS = "SET_WALLET_SETTINGS",
  SET_DEFAULT_CHANGE_INDEX = "SET_DEFAULT_CHANGE_INDEX",
  SET_USED_ADDRESSES_FILTER = "SET_USED_ADDRESSES_FILTER"
}
