export enum MUTATIONS {
  SET_WALLETS = "SET_WALLETS",
  SET_CURRENT_WALLET = "SET_CURRENT_WALLET",
  SET_CURRENT_ADDRESSES = "SET_CURRENT_ADDRESSES",
  UPDATE_BALANCES = "UPDATE_ADDRESSES_BALANCES",
  CALC_TOTAL_ERG_BALANCE = "CALC_TOTAL_ERG_BALANCE",
  SET_ERG_PRICE = "SET_ERG_PRICE"
}
